### ISSUE TITLE
Configure merge queue for the main branch

### ISSUE THREAD

**Issue by mnonnenmacher** [eclipse-apoapsis/.eclipsefdn#3]
Please enable the merge queue as part of the branch protection rules for the main branch as this can currently not be done via Otterdog (see https://github.com/eclipse-csi/otterdog/issues/86).

The required settings are:
Merge method: "Rebase and merge"
Maximum pull requests to build: 5
Minimum pull requests to merge: 1 or after 5 minutes
Maximum pull requests to merge: 5
Only merge non-failing pull requests: true
Consider check failed after: 60 minutes

**Comment by mnonnenmacher** [comment]
@netomi There is one issue with the merge queue that is caused by the global `eclipsefdn/eca` workflow. This workflow is required but not triggered by the merge queue, therefore it times out after a while (see https://github.com/eclipse-apoapsis/ort-server/pull/2):
> github-merge-queue bot removed this pull request from the merge queue due to no response for status checks

To solve this the `merge_group` event would have to be added as a [trigger](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#merge_group) to the workflow:

```yaml
on:
  merge_group:
    types: [checks_requested]
```

What would be the correct place to request such a change?

**Comment by netomi** [comment]
So the eclipsefdn/eca status check is not handled via a workflow but through a GitHub App that reacts on webhook events.
We will need to request that here: https://gitlab.eclipse.org/eclipsefdn/it/api/git-eca-rest-api

As a short term solution, we can remove the eclipsefdn/eca check from the list of required checks in the branch protection rule.
Change the line https://github.com/eclipse-apoapsis/.eclipsefdn/blob/main/otterdog/eclipse-apoapsis.jsonnet#L22

to 

```diff
-          required_status_checks+: [
+          required_status_checks: [
```

this does not inherit the eca check from the default config.

**Comment by netomi** [comment]
Created ticket: https://gitlab.eclipse.org/eclipsefdn/it/api/git-eca-rest-api/-/issues/161

**Comment by mnonnenmacher** [comment]
Thanks for the explanation and creating the ticket. I will apply the workaround for now.
